name: Deploy to AWS t3.micro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to your app directory (create if it doesn't exist)
            mkdir -p ~/blog-app
            cd ~/blog-app
            
            # Pull latest code
            git pull || git clone ${{ secrets.REPO_URL }} .
            
            # Update Node.js to a compatible version
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            
            # Install dependencies with legacy peer deps flag to resolve conflicts
            npm install --legacy-peer-deps
            
            # Make a small fix to package.json for date-fns compatibility
            sed -i 's/"date-fns": "4.1.0"/"date-fns": "3.6.0"/g' package.json
            
            # Reinstall with updated dependencies
            npm install --legacy-peer-deps
            
            # Build the application
            npx next build
            
            # Start/restart with PM2
            pm2 restart blog || pm2 start npm --name "blog" -- start