name: Deploy to AWS t3.micro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to your app directory (create if it doesn't exist)
            mkdir -p ~/blog-app
            cd ~/blog-app
            
            # Pull latest code
            git pull || git clone ${{ secrets.REPO_URL }} .
            
            # Update Node.js to a compatible version (if not already installed)
            if ! command -v node &> /dev/null || [ $(node -v | cut -d. -f1 | tr -d 'v') -lt 18 ]; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Fix dependency conflict in package.json
            sed -i 's/"date-fns": "4.1.0"/"date-fns": "3.6.0"/g' package.json
            
            # Install dependencies with legacy peer deps flag
            npm install --legacy-peer-deps
            
            # Build the application
            npx next build
            
            # Check if PM2 is installed, install it if not
            if ! command -v pm2 &> /dev/null; then
              # Install PM2 for the current user only to avoid permission issues
              npm install pm2 -g
            fi
            
            # Start or restart the application with PM2
            pm2 restart blog || pm2 start npm --name "blog" -- start
            
            # Save PM2 process list and set to start on reboot
            pm2 save
            
            # Display the status
            pm2 ls
            
            echo "Deployment completed successfully!"
